---
title: "Git/Github in RStudio Intro"
author: "Matthew E. Aiello-Lammens"
date: "6/8/2020"
output: html_document
---

# Make sure Git is installed

How do you know? 

* Have you installed it?
* Go to RStudio > Preferences > Git/SVN - are there paths to executables?
    * This can also be checked / setup using Tools > Global Options > Git/SVN

# Make a new project

Two ways to do this:

1. In upper left corner, click on the +R cube thingy
2. In upper right corner, click on the project icon (again, the R cube thing) and select "New Project"

# Version control the new project

In the project menu, select "Project Options ...". Then select "Git/SVN" and then "Version Control System" -> "Git"

# Practice

Make a new file. Save it. Go to the "Git" tab in the upper left quadrant of RStudio.

Follow this order:
1. Select your item (Staged) 
2. Once selected, go to your cart by pressing "Commit" - a new window will open
3. Buy your item by writing a "Commit message" and selecting "Commit" 

In that window that popped up, you can check your "History". 

## More practice

Make another file and make some edit the first one. Go to Git again.

# How can I add this local git repo to Github?

1. Go to github
2. Create a new repository
3. Look at the section titled - "…or push an existing repository from the command line"
4. Open the RStudio "Terminal"
5. Copy and past the two lines from 3 into the terminal

Now when you commit something, you will see that the "Push" and "Pull" arrows are no longer faded out!

Go ahead and Push!

## Practice with Pushing and Pulling

Make some changes and push them. 

**THEN**, go to the github repo and make some changes there, using the web interface. Commit them. Then go back to your RStudio and Pull.

We can also try to simulate an Error message with Pushing if we don't Pull first.

# Using an already existing Remote (that I have access to)

1. Go to the Github repo that will be your remote (origin) and copy the url
2. In RStudio, go to the R Projects menu, and select "New Project"
3. Use the third option, "Version Control"

Here's one we can practice with - https://github.com/mlammens/github_in_rstudio


